owner: tiagoaquinofl
repo: uptime

sites:
  - name: Casa
    description: Servidor pessoal residencial
    url: s.tiagoaquino.com
    check: "tcp-ping"
    port: 443
    tags: [residencial, principal]

status-website:
  baseUrl: /uptime
  logoUrl: https://tiagoaquino.com/logo.svg
  name: Monitoramento da Casa 🏠
  introTitle: "**Monitoramento da Casa** - status em tempo real dos serviços pessoais de Tiago Aquino"
  introMessage: |
    Esta página mostra o uptime e o desempenho dos meus serviços.
    Gerada automaticamente com [Upptime](https://upptime.js.org) e [GitHub Actions](https://github.com/features/actions).
  navbar:
    - title: Página Inicial
      href: /
    - title: GitHub
      href: https://github.com/tiagoaquinofl/uptime
    - title: Site pessoal
      href: https://tiagoaquino.com
  commitMessages:
    forcePush: true

notify:
  needs: response-time
  runs-on: ubuntu-latest
  steps:
    - name: Enviar alerta via Telegram se estiver fora do ar
      if: needs.response-time.outputs.summary != 'up'
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        MESSAGE="🚨 *ALERTA: Serviço Fora do Ar!*\n\n📍 *Casa*\n🔗 URL: s.tiagoaquino.com\n🕒 Horário: $(date -u '+%Y-%m-%d %H:%M:%S') UTC\n\n📊 Status: *Offline*\n\n👉 Acesse o status completo: https://tiagoaquinofl.github.io/uptime"
        curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
          -d chat_id=${TELEGRAM_CHAT_ID} \
          -d text="$MESSAGE" \
          -d parse_mode=Markdown
